on:
  push:
    paths:
      - versions.txt
  workflow_dispatch:
  
      
jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.v.outputs.VERSION }}
      libs: ${{ steps.libs.outputs.LIBS }}
      
    steps:
      - uses: actions/checkout@v3
      - id: v
        run: |
          echo "VERSION=$(tail -n 1 versions.txt)" >> $GITHUB_OUTPUT
      #- id: libs
      #  run: |
      #    echo "LIBS=$(cat pkgs.txt)" >> $GITHUB_OUTPUT
  build:
    needs: [get]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ needs.get.outputs.version }}' 
        
      - run: |
          cmd.exe /c "build.bat"
